-- ############################################################
-- TABLE 1: PARKING LOT METADATA (The "Static" Info)
-- ############################################################
CREATE TABLE IF NOT EXISTS public.parking_lots (
    id INTEGER PRIMARY KEY,            -- Matches facility id from parken-in-ulm.de
    name TEXT NOT NULL,                 -- e.g., 'Am Rathaus'
    total_spaces INTEGER DEFAULT 0,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.parking_lots IS 'Static information about parking garages in Ulm.';

ALTER TABLE public.parking_lots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous read access" ON public.parking_lots
    FOR SELECT USING (true);

-- ############################################################
-- TABLE 2: PARKING STATUS (The "Live" History)
-- ############################################################
CREATE TABLE IF NOT EXISTS public.parking_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id INTEGER REFERENCES public.parking_lots(id) ON DELETE CASCADE,
    current_occupancy INTEGER NOT NULL,
    vacant_spaces INTEGER NOT NULL,
    forecast_occupancy INTEGER,        -- Ready for ML model predictions
    fetched_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.parking_status IS 'Real-time occupancy logs fetched from parken-in-ulm.de.';

ALTER TABLE public.parking_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous read access" ON public.parking_status
    FOR SELECT USING (true);

-- ############################################################
-- PERFORMANCE: INDEX FOR REAL-TIME DASHBOARD
-- ############################################################
CREATE INDEX IF NOT EXISTS idx_status_latest_arrival
ON public.parking_status (lot_id, fetched_at DESC);

-- ############################################################
-- AUTOMATION: THE SELF-UPDATING TIMESTAMP TRIGGER
-- ############################################################
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_parking_lots_modtime ON public.parking_lots;
CREATE TRIGGER update_parking_lots_modtime
    BEFORE UPDATE ON public.parking_lots
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

-- ############################################################
-- FUNCTION: GET LATEST PARKING STATUS (for frontend initial load)
-- ############################################################
CREATE OR REPLACE FUNCTION get_latest_parking_status()
RETURNS TABLE (
    id INTEGER, name TEXT, total_spaces INTEGER,
    lat DOUBLE PRECISION, lon DOUBLE PRECISION,
    current_occupancy INTEGER, vacant_spaces INTEGER,
    forecast_occupancy INTEGER, fetched_at TIMESTAMPTZ
) AS $$
    SELECT DISTINCT ON (pl.id)
        pl.id, pl.name, pl.total_spaces, pl.lat, pl.lon,
        ps.current_occupancy, ps.vacant_spaces,
        ps.forecast_occupancy, ps.fetched_at
    FROM parking_lots pl
    LEFT JOIN parking_status ps ON ps.lot_id = pl.id
    ORDER BY pl.id, ps.fetched_at DESC;
$$ LANGUAGE sql STABLE;

-- ############################################################
-- REALTIME: Enable for parking_status (live frontend updates)
-- ############################################################
ALTER PUBLICATION supabase_realtime ADD TABLE parking_status;

-- ############################################################
-- TABLE 3: ROUTE SHAPES (GTFS polylines, refreshed weekly)
-- ############################################################
CREATE TABLE IF NOT EXISTS public.route_shapes (
    id SERIAL PRIMARY KEY,
    route_number INTEGER NOT NULL,
    direction TEXT NOT NULL,              -- 'inbound' / 'outbound'
    category INTEGER NOT NULL,            -- 1=tram, 5=bus
    coordinates JSONB NOT NULL,           -- [[lat, lon], ...]
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (route_number, direction)
);

COMMENT ON TABLE public.route_shapes IS 'GTFS route polylines from SWU, refreshed weekly.';

ALTER TABLE public.route_shapes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous read access" ON public.route_shapes
    FOR SELECT USING (true);

DROP TRIGGER IF EXISTS update_route_shapes_modtime ON public.route_shapes;
CREATE TRIGGER update_route_shapes_modtime
    BEFORE UPDATE ON public.route_shapes
    FOR EACH ROW
    EXECUTE PROCEDURE update_modified_column();

-- ############################################################
-- FUNCTION: GET ROUTE SHAPES (for frontend initial load)
-- ############################################################
CREATE OR REPLACE FUNCTION get_route_shapes()
RETURNS TABLE (
    route_number INTEGER, direction TEXT,
    category INTEGER, coordinates JSONB
) AS $$
    SELECT route_number, direction, category, coordinates
    FROM public.route_shapes
    ORDER BY route_number, direction;
$$ LANGUAGE sql STABLE;
